# Generated by Django 5.2.5 on 2025-09-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='code',
            new_name='symbol',
        ),
    ]
